### PR TITLE
Display response

### PR DESCRIPTION
**Pull request by EnoF**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/EnoF/con-rest/pull/38%23issuecomment-69165303%22%2C%20%22https%3A//github.com/EnoF/con-rest/pull/38%23issuecomment-69172833%22%2C%20%22https%3A//github.com/EnoF/con-rest/pull/38%23issuecomment-69176353%22%2C%20%22https%3A//github.com/EnoF/con-rest/pull/38%23issuecomment-69176372%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/EnoF/con-rest/pull/38%23issuecomment-69165303%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22deleting%20workflows%20isn%27t%20possible%20anymore%5Cr%5Cnfunctionallity%20needs%20to%20be%20moved%20from%20worklowOverview%20to%20workflow%22%2C%20%22created_at%22%3A%20%222015-01-08T11%3A04%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8627051%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/TheBay0r%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20rebased%20and%20squahsed%20your%20initial%20commits%2C%20since%20they%20were%20breaking.%20Latest%20changes%20of%20master%20are%20in%20this%20branch.%20%5Cr%5Cn%5Cr%5CnDeleting%20is%20also%20resolved.%22%2C%20%22created_at%22%3A%20%222015-01-08T12%3A25%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1508400%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/EnoF%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-01-08T13%3A04%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8627051%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/TheBay0r%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-08T13%3A05%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8627051%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/TheBay0r%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/TheBay0r%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8627051%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/TheBay0r'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/EnoF/con-rest/pull/38#issuecomment-69165303'>General Comment</a></b>
- <a href='https://github.com/TheBay0r'></a> deleting workflows isn't possible anymore
functionallity needs to be moved from worklowOverview to workflow
- <a href='https://github.com/EnoF'></a> I rebased and squahsed your initial commits, since they were breaking. Latest changes of master are in this branch.
Deleting is also resolved.

<a href='https://www.codereviewhub.com/EnoF/con-rest/pull/38?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/EnoF/con-rest/pull/38?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/EnoF/con-rest/pull/38?approve=0'></a>&nbsp;<a href='https://github.com/EnoF/con-rest/pull/38'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by EnoF** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/EnoF/con-rest/pull/38'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by TheBay0r** [comment]
deleting workflows isn't possible anymore
functionallity needs to be moved from worklowOverview to workflow

**Comment by EnoF** [comment]
I rebased and squahsed your initial commits, since they were breaking. Latest changes of master are in this branch. 

Deleting is also resolved.

**Comment by TheBay0r** [comment]
:+1:

**Comment by TheBay0r** [comment]
:shipit:

**Pull request merged**
